language: node_js
sudo: false
node_js:
  - "4.5.0"
  - "6.5.0"
env:
  - NODE_ENV=development
services:
  - mongodb

before_install:
  - npm i -g npm@'>=3.5.3'
  - npm -v
  - npm i -g bower
  - bower -v




